[package]
name = "squash"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
proc-macro-error = "1"
quote = "1"
reflect = "0.0.9"
syn = { version = "1", features = ["full", "extra-traits"] }